datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kube-prometheus-prometheus.prometheus.svc:9090
        access: proxy
        isDefault: true

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.homelab.localhost
