apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: airlock
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: "digest"
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: "airlock"
      images:
        - alias: airlock
          imageName: ghcr.io/agustinbravop/airlock:latest
