apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: roomix-onboarding
  namespace: argocd
spec:
  commonUpdateSettings:
    updateStrategy: "digest"
  writeBackConfig:
    method: argocd
  applicationRefs:
    - namePattern: "roomix-onboarding"
      images:
        - alias: roomix-onboarding
          imageName: ghcr.io/agustinbravop/roomix-onboarding:latest
