---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBJFslhcyc2K4Vy9pA7FyMPyFPVmmYXAdO24hkm7AC0PXj2bknf5HVoHCAq8npwR5YLp1HvBd+TElpRr6JlQ/EJG/7XIpKgsQN7UDad1mBF8Vj+Rm7OyU+cbWJj2Cfr7gw7z2JRh4FR5mI0M7o2rnf2bowYj12p0M8yzXC9wEP2TTlLaoN8R+15K6316gXvFXGam6vMzsaBQNkEsYatR3XRPJ47Fhr+AacI7N+wamiZW0zj/qjsr+ZKhesh5WYyf27CfDpctW6Mkjh6N3bse2ow9eyUWf/K1TLlZ1546IYO9V2vuRK6tm2cqyyPBB6xra70AyTRhHdcnBmgRB7s1LNtpWJNKtjMahXLr/DcG+ovx/6WVPQvYoU8dlp8Y6V+seB5HUbUG49smWKYwvRMSb16+rhyMCiABKxiOnLDEA45iaQRm29wql6ggqdH1uRWjoenXdOgxixeI05gaeHnd+BilXIQmr9NVFVVWp+Cdljmlsw6e74mOGmAbVZcTEYADKr+NzRY2YYmR6RBJnWSgeH5Um06bu9/mVV1LAY4i94HaPzPShsVO1HYuMSYaZ82vy7do2N1aP1hhmmC1PLXWby0e9zGWHj23BPxGFjGK56ZFmS9pCwvjSvefhqTvkkcY661V4yjG+PGuOPH41WeOOcaxRwVqDx9QqnH3g1iMle/Fe4roj/WNSLT+Kes9kPj1c1+UWFzmY0hLdugALou1R9UWlYpFPDjN3B1XBMNMmXmqJEKRzVKydxBONpHb9rRCNxMCxk4vw==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
