apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
  annotations:
    argocd.argoproj.io/refresh: hard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - name: website
          image: ghcr.io/agustinbravop/website:latest
          ports:
            - containerPort: 80
              name: http
