---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airlock
  namespace: airlock
spec:
  encryptedData:
    OPENAI_API_KEY: AgCT0kQUQuTH6ATRmyJpfjq0BjoQ5Dzs1eYLxZq8foT+iNw0Ln0dUEh7dN9dEoXeBnL+q/EnQZUpjbE2XO7BvLrdvsrjZk8V+EHZ3PBROAuCXuxxj0rvbkvQKpuLLq2OII3V/+AbXH1ghneKI+t9yOKq8tfqnM1qRisVI/fPqmJyPjX/PeasYdfYZ4F334t5fqurDcK3SPH1rqUQlIlTRORJW1iTf80sSRCQD9cakCNlZLPhahnB/+ZYxar/JKDE4qLpUYkwZ0GXavdsJ9nRYJFKbM2slwkpP9pJaANs6u+kV8xS1GW5Hnx9Wdl3+JKlh8vEa6DvpUtaOnB1n7r6YgjFhnbHpCbVpdmN9FJNdkJCgJIkYUAnMfQM8xAIwUtUiXerjnfx4SvQwUAZh1zSyXA8eFc9XUQQ7+Fcsc7xE1uaOgWhunmyT/2o3azlWunJNQva72jrmi5bTtfcsrM2o2pE04OdS6KSSdhUsKfD/XM3w1iVtJNvOwsZGwJVjvpXa4pUG2dMgtNWqdUPEn3bDyOnYgb4+QzgowOHfYAgfYyD8P7jNfjleeEjMKFNLYBwdR2BSHmLgioXYq9LJkgAOl6rARn4gkcXJtmefTAfcWz77vZAM79QOjHJ7r3HvTf/gl/3fZaPr9FQ2pn1n2rA5ape6vLl2zWBhTWsiyvsCCH6DODbpwknba8ztO0ueK3hRDLnEUm1t30xjDLHn9CX7xhvwT3bRTouA7c7mNUR65u457UAOenjYXm4oaOtbZ37r3Xqg5kM1QCvViWVQVi5MZAkH3f+vPAC1iH4A5JbCHnW8hNt5Y/ZyqQ4zl0lbJprRwigF3Sd7MFrYgHMR5RISXomYIZFuLgOfddmRBtBSjQ2QqBLTosgR0bFfFYECd3nQscnDOnaHvYbUsWeExA8yWi8csnJw+8tpg==
  template:
    metadata:
      name: airlock
      namespace: airlock
