---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airlock
  namespace: airlock
spec:
  encryptedData:
    OPENAI_API_KEY: AgCeh7iGKcdVYAqeU7LXhe9JyRsBaBlI/WT19eTr11ej2shYRMvb25OV9hfzK6EDhm2fnT7GMn4UobV5LwMWQ6MW6+0awTaH4gcJzYPqYpTX26nzxzit89ijt9VVugV+mTyrFQJbnMM5JAS0HtGgwLal4H0riRVsGyFj7CPfcfp+mX7CPpeL/dQY4xbYwb0z4FL4ugsyzk+B31FjCkaR8nB52i8iiGGP9pncH7c8cGXu2c9JxdFfGd+sHnJ3uIkKgnC3yyexu/D0h+RV4o+dxHsKJ5nBv3WX5UOuS2WknWWtXOaFWstjN2dEP5RX5ZSwtlDQPV1F+2CvonI/rtPdAQ7vBMxNfNWZ+1N6eqW+KAvxpcxD+snmWK8/HywjvKCPyMqt8nr1wDPga8kfLT/Qfnima4sxb7KQ49gURgc9E/nESCpxCkVB1+d23It/WIpaJ6Q/FIglGhNBH+Np/Dyb2kITxm9ZJ5OXmTCRJYZFhtaSI8WmKh8fJVB9vTBedd5MCEdRqd8OEprbcwdaTtLekqOxSzGldwcQ+cYFP2G/yWDM54/qlI9aygT1VaNkLL1gwyeCa0faQE6uIvUMmDKqga1o8se3vX0dcZ3IQqBkbHl7t2DsPTH1aUrGVQaWmgx6V3VXaoN8umIKHcl5p28JocHka/RDeOhu/ztmVweqdVkhbjjis5xRsRh39XMBX8/F2SVZwaqkP5wna0OWqZ0jbrn0clxzR9a+/3Yqt6qyJDCrr+j+3r/XuWPHoWS+0MNioPr5mgf8+/jvr7tH5xtqMNMfDtbS8Kac/fhstIYdYXw1Ifw5bdAeHKYowT+vfBWQtnI3eOubeYAkJ+vslxDdCXG4DYORPBxQU8gZBdMoATwfYBsh0YgufO2rINiZJWQdVXnR044gEHeDHtF+vk6zE07PtTdhs4a9sA==
  template:
    metadata:
      name: airlock
      namespace: airlock
